var no1 = 10.20;
var no2 = 20;
var result = no1 + no2;
console.log("Addition is " + result);
var sub = no1 - no2;
console.log("Sub is " + sub);
var mul = no1 * no2;
console.log("Mul is " + mul);
var div = no1 / no2;
console.log("Div is " + div);
